### ISSUE TITLE
Provide output of "ah lint" command as a pull request comment

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [keptn-contrib/artifacthub#77]
When executing `./ah lint --kind keptn .` locally, I'm getting the following output:

```
------------------------------------------------------------------------------------------------------------------------
✓ Zapier Integration 1.0.0 (zapier/1.0.0)
------------------------------------------------------------------------------------------------------------------------

Package lint SUCCEEDED!

✓ Name: Zapier Integration
✓ Display name: Zapier Integration
✓ Version: 1.0.0
! App version: *** NOT PROVIDED ***
✓ Description: Keptn integration with Zapier.com
✓ License: Apache-2.0
! Logo URL: *** NOT PROVIDED ***
✓ Home URL: https://keptn.sh/docs/integrations/
✓ Deprecated: false
✓ Pre-release: false
✓ Contains security updates: false
! Provider: *** NOT PROVIDED ***
✓ Readme: PROVIDED
✓ Keywords:
  - keptn
  - monitoring
  - zapier
✓ Links:
  - Name: Source | URL: https://zapier.com
! Maintainers: *** NOT PROVIDED ***
! Containers images: *** NOT PROVIDED ***
! Changes: *** NOT PROVIDED ***
✓ Recommendations:
  - https://artifacthub.io/packages/helm/keptn/keptn
! Screenshots: *** NOT PROVIDED ***
✓ Operator: false
✓ Install: PROVIDED

```

but for all 39 integrations.

I believe that we should provide this output as a pull request comment, but just for those integrations that are being changed within the Pull Request.

**Getting a list of changed files** can be achieved like this:
```yaml

      - name: Get changed files
        id: changed_files
        uses: jitterbit/get-changed-files@v1
        continue-on-error: true

```

you can access it using `"${{ steps.changed_files.outputs.all }}"` - see https://github.com/jitterbit/get-changed-files for more information

**Posting a PR comment** can be achieved like this:

```yaml
      - id: report_docker_build_to_pr
        name: Report Docker Build to PR
        if: (github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.repository)
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          recreate: true
          header: test
          message: |
            The following Docker Images have been built:
            * ${{ fromJSON(steps.docker_build.outputs.BUILD_METADATA)['image.name'] }}
            * ${{ fromJSON(steps.docker_build_initcontainer.outputs.BUILD_METADATA)['image.name'] }}
```

# Definition of Done

- [ ] GH Action that lints the artifacthub packages for each Pull Request and provides a PR comment
